### ISSUE TITLE
跑的时候，会报错啊

### ISSUE THREAD

**Issue by qiushi2012** [leowang721/k-react-native-form-demo#1]
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/react/k-react-native-form-demo-master/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/KFormSample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:490:13)
    at Object.execFileSync (child_process.js:510:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/react/k-react-native-form-demo-master/node_modules/promise/lib/core.js:45:5)

**Comment by leowang721** [comment]
不好意思，近期都忙于工作……
我这就看一下罢…… 
汗...

**Comment by leowang721** [comment]
刚刚测试了一下，你可以直接按照此文的方法来处理这个问题：http://www.jianshu.com/p/a74aec74fd4e
直接用xcode打开project进行处理

**Comment by leowang721** [comment]
代码已更新
